module.exports = {
  title: "blogstr",
  description:
    "A minimalist blog on nostr that allows anyone to easily create their own personal micro-blog.",
  favicon:
  "/images/skunkworks_logo-removebg-preview.png",
  logo: "/images/skunkworks_logo-removebg-preview.png",
  npub: "npub19gu60un37syleegfssgx2ystmh365h0stuflqxy64mnp77p9htps2aldk8",
  themes: [
    "light",
    "dark",
    "cupcake",
    "bumblebee",
    "emerald",
    "corporate",
    "synthwave",
    "retro",
    "cyberpunk",
    "valentine",
    "halloween",
    "garden",
    "forest",
    "aqua",
    "lofi",
    "pastel",
    "fantasy",
    "wireframe",
    "black",
    "luxury",
    "dracula",
    "cmyk",
    "autumn",
    "business",
    "acid",
    "lemonade",
    "night",
    "coffee",
    "winter",
  ],
  customThemes: [
    {
      custom: {
        primary: "#ef7951",
        secondary: "#ea0eb3",
        accent: "#9d66d1",
        neutral: "#1D252B",
        "base-100": "#403B59",
        info: "#A0BEE4",
        success: "#12825D",
        warning: "#C87114",
        error: "#E9445F",
      },
    },
  ],
  relays: [
    "wss://nos.lol",
    "wss://nostr-pub.wellorder.net",
    "wss://nostr-01.yakihonne.com",
    "wss://nostr-02.dorafactory.org",
    "wss://relay.snort.social",
    "wss://relay.damus.io",
    "wss://nostr.wine",
    "wss://nostr.nostrelay.org",
    "wss://relay.nostr.ch",
    "wss://nostr.bitcoiner.social",
    "wss://nostr.onsats.org",
    "wss://nostr-relay.wlvs.space",
    "wss://nostr.zebedee.cloud",
    "wss://relay.nostr.info",
  ],
};
